#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-durian
Version  : 1.2.0
Release  : 1
URL      : https://repo1.maven.org/maven2/com/diffplug/durian/durian-core/1.2.0/durian-core-1.2.0-sources.jar
Source0  : https://repo1.maven.org/maven2/com/diffplug/durian/durian-core/1.2.0/durian-core-1.2.0-sources.jar
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-durian-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-durian package.
Group: Data

%description data
data components for the mvn-durian package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/diffplug/durian/durian-core/1.2.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/diffplug/durian/durian-core/1.2.0/durian-core-1.2.0-sources.jar


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/diffplug/durian/durian-core/1.2.0/durian-core-1.2.0-sources.jar
